"""initial tables

Creates all eleven tables from PROJECT_PLAN.md section 4.

Two details are deliberate and must survive any regeneration of this file:
  * ``uq_vet_active_slot`` is a PARTIAL unique index -- it only applies to
    REQUESTED/CONFIRMED appointments, so a cancelled slot can be rebooked while
    the cancelled row is kept as history.
  * enums are rendered as VARCHAR + CHECK (``native_enum=False``) so SQLite and
    PostgreSQL behave identically and no ALTER TYPE migration is ever needed.

Revision ID: ceb7d6b7c1cf
Revises: 
Create Date: 2026-08-22 23:19:55.273638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceb7d6b7c1cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source_type', sa.Enum('CLINIC', 'EXTERNAL', name='source_type', native_enum=False, length=16), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('source_path', sa.String(length=500), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_path')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'VET', 'CLIENT', name='role', native_enum=False, length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('client_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('chroma_id', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chroma_id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_chunk_document_index')
    )
    op.create_table('vet_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=True),
    sa.Column('license_no', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_no'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('species', sa.String(length=40), nullable=False),
    sa.Column('breed', sa.String(length=80), nullable=True),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'UNKNOWN', name='sex', native_enum=False, length=16), server_default='UNKNOWN', nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('weight_kg IS NULL OR weight_kg >= 0', name='ck_pets_weight_non_negative'),
    sa.ForeignKeyConstraint(['owner_id'], ['client_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.create_index('ix_pets_owner_id', ['owner_id'], unique=False)

    op.create_table('time_off',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vet_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.CheckConstraint('ends_at > starts_at', name='ck_time_off_end_after_start'),
    sa.ForeignKeyConstraint(['vet_id'], ['vet_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_off', schema=None) as batch_op:
        batch_op.create_index('ix_time_off_vet_starts_at', ['vet_id', 'starts_at'], unique=False)

    op.create_table('vet_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vet_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_minutes', sa.Integer(), server_default='30', nullable=False),
    sa.CheckConstraint('end_time > start_time', name='ck_availability_end_after_start'),
    sa.CheckConstraint('slot_minutes > 0', name='ck_availability_slot_minutes_positive'),
    sa.CheckConstraint('weekday >= 0 AND weekday <= 6', name='ck_availability_weekday_range'),
    sa.ForeignKeyConstraint(['vet_id'], ['vet_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vet_availability', schema=None) as batch_op:
        batch_op.create_index('ix_vet_availability_vet_weekday', ['vet_id', 'weekday'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('vet_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='appointment_status', native_enum=False, length=16), server_default='CONFIRMED', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name='ck_appointments_end_after_start'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vet_id'], ['vet_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index('ix_appointments_pet_starts_at', ['pet_id', 'starts_at'], unique=False)
        batch_op.create_index('ix_appointments_vet_starts_at', ['vet_id', 'starts_at'], unique=False)
        batch_op.create_index('uq_vet_active_slot', ['vet_id', 'starts_at'], unique=True, sqlite_where=sa.text("status IN ('REQUESTED', 'CONFIRMED')"), postgresql_where=sa.text("status IN ('REQUESTED', 'CONFIRMED')"))

    op.create_table('medical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('vet_id', sa.Integer(), nullable=True),
    sa.Column('visit_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vet_id'], ['vet_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.create_index('ix_medical_records_pet_visit_date', ['pet_id', 'visit_date'], unique=False)

    op.create_table('vaccinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('vaccine_name', sa.String(length=120), nullable=False),
    sa.Column('given_at', sa.Date(), nullable=False),
    sa.Column('due_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vaccinations', schema=None) as batch_op:
        batch_op.create_index('ix_vaccinations_pet_due_at', ['pet_id', 'due_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccinations', schema=None) as batch_op:
        batch_op.drop_index('ix_vaccinations_pet_due_at')

    op.drop_table('vaccinations')
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_index('ix_medical_records_pet_visit_date')

    op.drop_table('medical_records')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index('uq_vet_active_slot', sqlite_where=sa.text("status IN ('REQUESTED', 'CONFIRMED')"), postgresql_where=sa.text("status IN ('REQUESTED', 'CONFIRMED')"))
        batch_op.drop_index('ix_appointments_vet_starts_at')
        batch_op.drop_index('ix_appointments_pet_starts_at')

    op.drop_table('appointments')
    with op.batch_alter_table('vet_availability', schema=None) as batch_op:
        batch_op.drop_index('ix_vet_availability_vet_weekday')

    op.drop_table('vet_availability')
    with op.batch_alter_table('time_off', schema=None) as batch_op:
        batch_op.drop_index('ix_time_off_vet_starts_at')

    op.drop_table('time_off')
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_index('ix_pets_owner_id')

    op.drop_table('pets')
    op.drop_table('vet_profiles')
    op.drop_table('knowledge_chunks')
    op.drop_table('client_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('knowledge_documents')
    # ### end Alembic commands ###
